{
“Agriculture Education”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/agriculturenatural-resources-career-cluster”,
“Automotive Technology”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/automotive-technology”,
“Biomedical (PLTW)”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/biomedical-pltw”,
“Business Management (HSOB)”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/business-management”,
“Collision Repair & Refinishing”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/collision-repair-refinishing”,
“Construction Technology”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/construction-technology”,
“Computer Repair & Networking”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/computer-repair-networking”,
“Computer Science (PLTW)”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/computer-science”,
“Culinary Arts”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/culinary-arts”,
“Early Childhood Careers”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/early-childhood-careers”,
“Engineering (PLTW)”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/engineering-pltw”,
“Family & Consumer Science”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/family-consumer-science”,
“Machining Technology”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/machining-technology”,
“Teaching Professions”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/teaching-professions”,
“Welding Technology”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/welding-technology”,
“English IV Integrated & Math IV Integrated”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/english-iv-integrated-math-iv-integrated”,
“Counseling”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/counseling”,
“Special & Resource Education”: “https://sites.google.com/lebanon.k12.mo.us/ltcc/academics/special-resource-education”,
}
